#!/bin/sh

#pid=$(sudo netstat -tulpn | sed -n "/3001/p" | sed -rn 's/.*([0-9]*)/node.*/\1/gp';) && kill ${pid}
#pid=$(sudo netstat -tulpn | sed -n "/3000/p" | sed -rn 's/.*([0-9]*)/node.*/\1/gp';) && kill ${pid}


pid=$( netstat -tulpn | sed -n "/3000/p" | sed -rn 's/.*\s([0-9]*)\/node.*/\1/gp';) && kill ${pid}
pid=$( netstat -tulpn | sed -n "/3001/p" | sed -rn 's/.*\s([0-9]*)\/node.*/\1/gp';) && kill ${pid}

